### ISSUE TITLE
PA Review: Topics/Tags

### ISSUE THREAD

**Issue by tkettle220** [tkettle220/quora-clone#21]

**Comment by s-pangburn** [comment]
Seems to work great! Excellent job with the seed data, the descriptions are a nice touch 👍

**Comment by s-pangburn** [comment]
Oh, when searching topics, there should be slightly more padding on the sides, maybe just a couple pixels. Plus, the entire div should be clickable, and should set `cursor: pointer`

Again, not mission critical, so you can get to that whenever you like.

**Comment by tkettle220** [comment]
fixed!
